services:
  postgres:
    image: postgres:17.5
    container_name: chat_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.0.2
    container_name: chat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
